env:
  browser: true
  es2021: true
  node: true
extends:
  - google
parserOptions:
  ecmaVersion: latest
rules: {
  operator-linebreak: [
    "error",
    "after", {
      "overrides": {
          "?": "before",
          ":": "before"
        }
    }
  ]
}
